### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by FlorentMasson** [GameAnalytics/GA-SDK-CORDOVA#6]
Hi,
I'm trying to make it work with cordova-android 8.1.0, cordova-plugin-gameanalytics 3.0.9. My device is Android 8.0.0.
I can't get any event on the live feed.
I have this error in logcat
```
2020-05-27 23:46:56.501 23693-23981/ I/GameAnalytics: Info/GameAnalytics: Info logging enabled
2020-05-27 23:46:56.510 23693-23969/ W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/instantapps/InstantApps;
2020-05-27 23:46:56.510 23693-23969/ W/System.err:     at com.gameanalytics.sdk.GAPlatform.initializeWithActivity(GAPlatform.java:77)
2020-05-27 23:46:56.510 23693-23969/ W/System.err:     at com.gameanalytics.sdk.GameAnalytics.initializeWithGameKey(GameAnalytics.java:360)
2020-05-27 23:46:56.510 23693-23969/ W/System.err:     at com.gameanalytics.sdk.cordova.GameAnalyticsCordova.execute(GameAnalyticsCordova.java:162)
2020-05-27 23:46:56.510 23693-23969/ W/System.err:     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
2020-05-27 23:46:56.511 23693-23969/ W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
2020-05-27 23:46:56.511 23693-23969/ W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
2020-05-27 23:46:56.511 23693-23969/ W/System.err:     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
2020-05-27 23:46:56.511 23693-23969/ W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2020-05-27 23:46:56.511 23693-23969/ W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:325)
2020-05-27 23:46:56.511 23693-23969/ W/System.err:     at android.os.Looper.loop(Looper.java:142)
2020-05-27 23:46:56.511 23693-23969/ W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)
2020-05-27 23:46:56.515 23693-23969/ W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.instantapps.InstantApps" on path: DexPathList[[zip file "/data/app/-W3rKePH0wBfL5FAASZmqYw==/base.apk"],nativeLibraryDirectories=[/data/app/-W3rKePH0wBfL5FAASZmqYw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
2020-05-27 23:46:56.515 23693-23969/ W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
2020-05-27 23:46:56.516 23693-23969/ W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2020-05-27 23:46:56.516 23693-23969/ W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2020-05-27 23:46:56.516 23693-23969/ W/System.err: 	... 11 more
2020-05-27 23:46:56.523 23693-23693/ D/BezellessGripSuppressionFilter: getdisplaysize, x : 1440 y : 2880
2020-05-27 23:46:56.525 23693-23693/ D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-gameanalytics/www/GameAnalytics.js: Line 71 : GameAnalytics.initialize
2020-05-27 23:46:56.525 23693-23693/ I/chromium: [INFO:CONSOLE(71)] "GameAnalytics.initialize", source: file:///android_asset/www/plugins/cordova-plugin-gameanalytics/www/GameAnalytics.js (71)
``` 
The callback onComplete for initialisation is never executed so I guess the initialisation is not actually done.

**Comment by the1schwartz** [comment]
Thanks for reporting this. The android dependency to our native library has been updated which should fix this issue.
